### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by klange612** [klange612/shirts4mike2#1]
### Items to complete

_Complete these_
- [x] First things first
- [x] then you follow that up
- [ ] complete this final one and you're done

:1234:
